import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import MobileBar from "./components/MobileBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "YumYum",
  description: "Generated by create next app",
  manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <main className="min-h-screen pt-20 lg:pt-28 bg-white">{children}</main>
        <MobileBar/>
      </body>
    </html>
  );
}
